import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavMain from "@/components/nav-main";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex justify-center">
          <NavMain className="" />
        </header>
        <div className="font-sans grid grid-rows-[20px_1fr_20px] items-center justify-items-center p-1 pb-20">
          <main className="flex flex-col gap-[16px] row-start-2 items-center sm:items-start mt-20">
            {children}

          </main>
        </div>
      </body>
    </html>
  );
}
